[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:scrape-vlopses]
command=/home/user/.venv/bin/python3 /home/user/app/scrape_vlopses.py
directory=/data/
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
startsecs=0
autostart=true
autorestart=false

[program:spark-master]
command=/bin/bash -c '/opt/spark/sbin/start-master.sh -h 0.0.0.0 -p 7077 --webui-port %(ENV_SPARK_MASTER_UI_PORT)s && /opt/spark/sbin/start-thriftserver.sh --master spark://127.0.0.1:7077 --conf spark.ui.port=%(ENV_SPARK_THRIFT_PORT)s --conf spark.sql.legacy.timeParserPolicy=LEGACY --executor-memory 8G && mkdir -p /tmp/spark && /opt/spark/sbin/start-worker.sh -h 0.0.0.0 --webui-port 8081 -d /tmp/spark spark://127.0.0.1:7077 -m $(/home/user/.venv/bin/python3 -c "import psutil; print(\"%%dg\" %% int(0.8 * psutil.virtual_memory().total / (1024**3)))")'
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
startsecs=0
autostart=true
autorestart=false

[program:fastapi-celery]
command=/home/%(ENV_DOCKER_USER)s/.venv/bin/celery -A main_celery worker -c 1 -P threads -Q dsa_tdb_queue --loglevel=INFO
directory=/home/%(ENV_DOCKER_USER)s/
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:fastapi-celery-flower]
command=/home/%(ENV_DOCKER_USER)s/.venv/bin/celery -A main_celery --broker=%(ENV_CELERY_BROKER_URL)s flower --port=%(ENV_CELERY_FLOWER_PORT)s
directory=/home/%(ENV_DOCKER_USER)s/
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:fastapi-webapp]
command=/home/%(ENV_DOCKER_USER)s/.venv/bin/python3 main_fastapi.py
directory=/home/%(ENV_DOCKER_USER)s/
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:notebook]
command=/home/%(ENV_DOCKER_USER)s/.venv/bin/python3 -m jupyter lab --ip='*' --port=%(ENV_JUPYTER_PORT)s --no-browser -y --allow-root --NotebookApp.token=''
directory=/notebooks
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
