[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:superset-celery]
command=/home/%(ENV_DOCKER_USER)s/.local/share/pipx/venvs/apache-superset/bin/celery --app=superset.tasks.celery_app:app worker --pool=prefork -O fair -c 4
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autostart=true

[program:superset-app]
command=/bin/bash /home/%(ENV_DOCKER_USER)s/init_superset.sh
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autostart=true
environment=HOME=/home/%(ENV_DOCKER_USER)s,USER=%(ENV_DOCKER_USER)s
